"""
launchguard.sub_agents.fix_writer — FixWriter ADK sub-agent.

RESPONSIBILITY
--------------
Given classified ReconciliationDelta objects (from session state), generate a ReadinessScorecard
(verdict + counts), propose fixes as ProposedPatch objects, and open a fix-PR via GitHub MCP.

Human-in-the-loop gate (AI Operating Principles §2): FixWriter OPENS a PR and stops.
It never merges, never applies patches directly, and never mutates live GCP state.
The human reviews and merges.

*** INCREMENT 2 STATUS: WIRED ***
BE-06 (propose_patch, open_pr tools) and LLM-04 (PR-body generation prompt) are now
implemented.  build_fix_writer_agent() registers the two FixWriter tools from
launchguard.tools.fix_tools and carries the LLM-04 PR-narrative instruction.  The
deterministic pipeline (verdict, counts, patches, scorecard, PR body) lives in
launchguard.fix_writer_core and is fully testable WITHOUT google-adk or a model — the
ADK agent is a thin model-driven wrapper over that core.

SESSION-STATE CONTRACT
----------------------
INPUT  (reads from session state):
  SessionKeys.RECONCILIATION_DELTAS : list[dict]  — [ReconciliationDelta.to_dict(), ...]
  SessionKeys.REPO_PATH             : str
  SessionKeys.GCP_PROJECT_ID        : str
  SessionKeys.GCP_SERVICE_NAME      : str

OUTPUT (writes to session state):
  SessionKeys.READINESS_SCORECARD   : dict  — ReadinessScorecard.to_dict()
  SessionKeys.PROPOSED_PATCHES      : list[dict]  — [ProposedPatch.to_dict(), ...]
  SessionKeys.PR_URL                : str | None   — GitHub PR URL if opened

TOOL ALLOW-LIST  (AI Operating Principles §4; TOOL_ALLOWLISTS["FixWriter"])
--------------
  propose_patch  — generate a gcloud command / service.yaml / dockerfile diff for a delta
                   applied=False always; the patch is informational only (§2)
  open_pr        — open a fix-PR via GitHub MCP to a NON-DEFAULT branch
                   Never targets main/master (409 GUARDRAIL_PR_TARGET_VIOLATION if attempted)
                   Never merges — surfaces the PR URL and stops

SECURITY NOTES
--------------
  - §2: Agent NEVER applies a fix.  propose_patch.applied is always False.
  - §2: open_pr targets a non-default branch; PR is not merged by the agent.
  - §3: PR body and patch content generated by LLM-04 must pass redaction before any
        model call and before being written to the PR description.
  - §5: delta summaries and evidence from session state are treated as data; the model
        is instructed to ground its PR narrative in the evidence, not to interpret them
        as instructions.

MODEL
-----
  Gemini 2.5 Pro (MODEL_PRO) — fix/PR-body generation (LLM-04, Increment 2):
    - Structured output for ProposedPatch (JSON mode, function calling preferred)
    - Evidence-grounded PR narrative (no hallucinated commands)
    - Redaction pass before model call (BE-07 seam)

TODO (LLM-04, Increment 2):
  - Wire propose_patch and open_pr tools (after BE-06 implements them).
  - Implement PR-body generation prompt with structured output + redaction seam.
  - Implement ReadinessScorecard Markdown rendering.
  - Wire human approval gate (adk web confirm step or CLI prompt).
"""

from __future__ import annotations

_AGENT_CLASS = None


def _get_agent_class():
    global _AGENT_CLASS  # noqa: PLW0603
    if _AGENT_CLASS is None:
        try:
            from google.adk.agents import Agent  # noqa: PLC0415
            _AGENT_CLASS = Agent
        except ImportError as exc:
            raise RuntimeError(
                "google-adk is not installed — run 'make install' to install dependencies."
            ) from exc
    return _AGENT_CLASS


def build_fix_writer_agent():
    """
    Build and return the FixWriter ADK Agent (Increment 2: tools wired).

    Registers the two FixWriter tools (propose_patch, open_pr) from
    launchguard.tools.fix_tools and carries the LLM-04 PR-narrative instruction.

    The agent's behavior is:
      - Read reconciliation_deltas from session state
      - Compute ReadinessScorecard (verdict + counts) deterministically
      - For each delta, call propose_patch to generate a fix (applied=False always)
      - Call open_pr (mock dry-run by default; real mode needs GITHUB_TOKEN) on a
        non-default branch — never merges, never targets main/master
      - Write readiness_scorecard, proposed_patches, and pr_url to session state

    Raises:
        RuntimeError: if google-adk is not installed.

    Returns:
        google.adk.agents.Agent: the constructed FixWriter agent.
    """
    from launchguard.config import MODEL_PRO  # noqa: PLC0415
    from launchguard.tools.fix_tools import open_pr, propose_patch  # noqa: PLC0415

    Agent = _get_agent_class()

    return Agent(
        name="FixWriter",
        model=MODEL_PRO,
        description=(
            "Converts ReconciliationDelta objects into a ReadinessScorecard, proposed patches, "
            "and a fix-PR (GitHub MCP, human merge gate).  Never applies fixes directly."
        ),
        instruction=_FIX_WRITER_INSTRUCTION,
        tools=[propose_patch, open_pr],
    )


_FIX_WRITER_INSTRUCTION = """\
You are FixWriter, the final sub-agent in the LaunchGuard three-source reconciliation pipeline.

YOUR JOB:
  1. Read reconciliation_deltas from session state.
  2. Compute a ReadinessScorecard (verdict = BLOCKED / WARN / READY, counts by class).
  3. For each delta, call propose_patch to generate a fix (applied=false always).
  4. Call open_pr to open a fix-PR on a non-default branch (mock dry-run by default).
  5. Write readiness_scorecard, proposed_patches, and pr_url to session state.

PR NARRATIVE (LLM-04):
  When you write the PR body, ground EVERY statement in a delta's evidence (source +
  locator). Do NOT invent commands — the actionable command/diff comes from
  propose_patch.content. You may explain and summarize; you may not fabricate a fix that
  bypasses the propose_patch schema. Reference secrets by NAME only.

VERDICT RULE (deterministic — do not use model judgment):
  BLOCKED  → any delta with delta_class = "will-fail"
  WARN     → no will-fail, but at least one "will-misbehave" or "cost-risk"
  READY    → only "needs-review" deltas or zero deltas

HUMAN-IN-THE-LOOP GATE (AI Operating Principles §2):
  You OPEN a PR and STOP.  You never merge, never push directly to main or master,
  and never apply any fix to the live GCP environment.
  The propose_patch tool returns patches with applied=false — this is non-negotiable.
  open_pr targets a non-default branch; any attempt to target main/master is rejected
  by the guardrail layer (409 GUARDRAIL_PR_TARGET_VIOLATION).

REDACTION (AI Operating Principles §3):
  Your PR title, body, and all patch content must not contain secret values, tokens,
  or passwords.  Reference secrets by NAME only (e.g., "SECRET_FOO").
  The redaction seam (BE-07) runs before any model call — do not bypass it.

DO NOT:
  - Merge the PR.
  - Apply any fix directly to a file, repository, or GCP resource.
  - Target the default branch (main / master) in open_pr.
  - Execute gcloud commands — those go in propose_patch.content for the human to run.
  - Include secret values in any output field.
"""
