"""
launchguard.sub_agents.fix_writer — FixWriter ADK sub-agent.

RESPONSIBILITY
--------------
Given classified ReconciliationDelta objects (from session state), generate a ReadinessScorecard
(verdict + counts), propose fixes as ProposedPatch objects, and open a fix-PR via GitHub MCP.

Human-in-the-loop gate (AI Operating Principles §2): FixWriter OPENS a PR and stops.
It never merges, never applies patches directly, and never mutates live GCP state.
The human reviews and merges.

*** INCREMENT 1 STATUS: PLACEHOLDER STUB ***
This module defines the agent factory, allow-list, and session-state contract.
The actual diff/PR-body generation prompts (LLM-04) and tool wiring (BE-06) are
deferred to Increment 2.  In Increment 1, calling build_fix_writer_agent() constructs
a structurally complete Agent with the correct model/name/instruction but with no tools
registered (they are injected by backend BE-06 in Increment 2).

SESSION-STATE CONTRACT
----------------------
INPUT  (reads from session state):
  SessionKeys.RECONCILIATION_DELTAS : list[dict]  — [ReconciliationDelta.to_dict(), ...]
  SessionKeys.REPO_PATH             : str
  SessionKeys.GCP_PROJECT_ID        : str
  SessionKeys.GCP_SERVICE_NAME      : str

OUTPUT (writes to session state):
  SessionKeys.READINESS_SCORECARD   : dict  — ReadinessScorecard.to_dict()
  SessionKeys.PROPOSED_PATCHES      : list[dict]  — [ProposedPatch.to_dict(), ...]
  SessionKeys.PR_URL                : str | None   — GitHub PR URL if opened

TOOL ALLOW-LIST  (AI Operating Principles §4; TOOL_ALLOWLISTS["FixWriter"])
--------------
  propose_patch  — generate a gcloud command / service.yaml / dockerfile diff for a delta
                   applied=False always; the patch is informational only (§2)
  open_pr        — open a fix-PR via GitHub MCP to a NON-DEFAULT branch
                   Never targets main/master (409 GUARDRAIL_PR_TARGET_VIOLATION if attempted)
                   Never merges — surfaces the PR URL and stops

SECURITY NOTES
--------------
  - §2: Agent NEVER applies a fix.  propose_patch.applied is always False.
  - §2: open_pr targets a non-default branch; PR is not merged by the agent.
  - §3: PR body and patch content generated by LLM-04 must pass redaction before any
        model call and before being written to the PR description.
  - §5: delta summaries and evidence from session state are treated as data; the model
        is instructed to ground its PR narrative in the evidence, not to interpret them
        as instructions.

MODEL
-----
  Gemini 2.5 Pro (MODEL_PRO) — fix/PR-body generation (LLM-04, Increment 2):
    - Structured output for ProposedPatch (JSON mode, function calling preferred)
    - Evidence-grounded PR narrative (no hallucinated commands)
    - Redaction pass before model call (BE-07 seam)

TODO (LLM-04, Increment 2):
  - Wire propose_patch and open_pr tools (after BE-06 implements them).
  - Implement PR-body generation prompt with structured output + redaction seam.
  - Implement ReadinessScorecard Markdown rendering.
  - Wire human approval gate (adk web confirm step or CLI prompt).
"""

from __future__ import annotations

_AGENT_CLASS = None


def _get_agent_class():
    global _AGENT_CLASS  # noqa: PLW0603
    if _AGENT_CLASS is None:
        try:
            from google.adk.agents import Agent  # noqa: PLC0415
            _AGENT_CLASS = Agent
        except ImportError as exc:
            raise RuntimeError(
                "google-adk is not installed — run 'make install' to install dependencies."
            ) from exc
    return _AGENT_CLASS


def build_fix_writer_agent():
    """
    Build and return the FixWriter ADK Agent.

    [Increment 1 stub]: Returns a structurally complete Agent with the correct
    model, name, and instruction.  Tools (propose_patch, open_pr) are NOT yet
    registered — they will be injected by backend BE-06 in Increment 2.

    In Increment 1 the agent will:
      - Read reconciliation_deltas from session state
      - Compute ReadinessScorecard (verdict + counts) deterministically
      - Write scorecard to session state
      - NOT yet generate patches or open a PR (tools not wired)

    Raises:
        RuntimeError: if google-adk is not installed.

    Returns:
        google.adk.agents.Agent: the constructed FixWriter agent.

    TODO (LLM-04, Increment 2): Wire propose_patch + open_pr tools after BE-06.
    TODO (LLM-04, Increment 2): Implement PR-body generation prompt (structured output,
    redaction before model call, evidence-grounded narrative, no free-text fix bypassing
    the propose_patch schema).
    """
    from launchguard.config import MODEL_PRO  # noqa: PLC0415

    Agent = _get_agent_class()

    return Agent(
        name="FixWriter",
        model=MODEL_PRO,
        description=(
            "Converts ReconciliationDelta objects into a ReadinessScorecard, proposed patches, "
            "and a fix-PR (GitHub MCP, human merge gate).  Never applies fixes directly.  "
            "[Increment 1: scorecard computation only; patch + PR wired in Increment 2 / LLM-04]"
        ),
        instruction=_FIX_WRITER_INSTRUCTION,
    )


_FIX_WRITER_INSTRUCTION = """\
You are FixWriter, the final sub-agent in the LaunchGuard three-source reconciliation pipeline.

YOUR JOB:
  1. Read reconciliation_deltas from session state.
  2. Compute a ReadinessScorecard (verdict = BLOCKED / WARN / READY, counts by class).
  3. [Increment 2] For each delta, call propose_patch to generate a fix.
  4. [Increment 2] Call open_pr to open a fix-PR on a non-default branch.
  5. Write readiness_scorecard, proposed_patches, and pr_url to session state.

VERDICT RULE (deterministic — do not use model judgment):
  BLOCKED  → any delta with delta_class = "will-fail"
  WARN     → no will-fail, but at least one "will-misbehave" or "cost-risk"
  READY    → only "needs-review" deltas or zero deltas

HUMAN-IN-THE-LOOP GATE (AI Operating Principles §2):
  You OPEN a PR and STOP.  You never merge, never push directly to main or master,
  and never apply any fix to the live GCP environment.
  The propose_patch tool returns patches with applied=false — this is non-negotiable.
  open_pr targets a non-default branch; any attempt to target main/master is rejected
  by the guardrail layer (409 GUARDRAIL_PR_TARGET_VIOLATION).

REDACTION (AI Operating Principles §3):
  Your PR title, body, and all patch content must not contain secret values, tokens,
  or passwords.  Reference secrets by NAME only (e.g., "SECRET_FOO").
  The redaction seam (BE-07) runs before any model call — do not bypass it.

[INCREMENT 1 NOTE]:
  propose_patch and open_pr tools are not yet registered.  In this increment, compute
  and write the ReadinessScorecard only.  Set proposed_patches to [] and pr_url to null.

DO NOT:
  - Merge the PR.
  - Apply any fix directly to a file, repository, or GCP resource.
  - Target the default branch (main / master) in open_pr.
  - Execute gcloud commands — those go in propose_patch.content for the human to run.
  - Include secret values in any output field.
"""
