"""
launchguard.sub_agents.reconciler — Reconciler ADK sub-agent.

RESPONSIBILITY
--------------
Diff the three normalized state objects (IntendedContract, DeclaredState, LiveState) and
produce a list of classified ReconciliationDelta objects — one per detected discrepancy.

This is the CORE IP of LaunchGuard.  Detection is DETERMINISTIC (parsing + rules, BE-05).
Gemini 2.5 Pro is used ONLY for:
  (a) classifying genuine ambiguity when no deterministic rule fires (LLM-03, Increment 2)
  (b) generating the human-readable summary/recommendation per delta

Key design principle (architecture.md §2): "deterministic core, model at the edges."
Findings must be reproducible — same inputs → same deltas (AI Operating Principles §6).

SESSION-STATE CONTRACT
----------------------
INPUT  (reads from session state):
  SessionKeys.INTENDED_CONTRACT : dict  — IntendedContract.from_dict()
  SessionKeys.DECLARED_STATE    : dict  — DeclaredState.from_dict()
  SessionKeys.LIVE_STATE        : dict  — LiveState.from_dict()

OUTPUT (writes to session state):
  SessionKeys.RECONCILIATION_DELTAS : list[dict]  — [ReconciliationDelta.to_dict(), ...]

TOOL ALLOW-LIST  (AI Operating Principles §4; TOOL_ALLOWLISTS["Reconciler"])
--------------
  EMPTY — Reconciler has NO external tool calls.
  All detection runs on in-memory schema-validated state objects (BE-05 rule engine).
  The Gemini ambiguity layer (LLM-03) is an internal model call, not a registered tool.

DETECTOR RULES  (BE-05 implements; Reconciler orchestrates)
--------------
  [KILLER]  secret-ref-without-secretAccessor — code refs secret X; SA lacks secretAccessor
            → will-fail, high confidence (the hero finding)
            secret-declared-not-created       — declared secret X not in Live secrets list
            port-mismatch                     — Intended port != Declared container_port
            host-not-0.0.0.0                  — app binds to localhost, Cloud Run needs 0.0.0.0
            missing-health-probe              — expects_health_probe=True, has_liveness_probe=False
            missing-startup-probe             — expects_startup_probe=True, has_startup_probe=False
            pid1-signal-unsafe                — shell-form CMD → PID1 won't forward signals
            over-broad-sa-role                — SA has roles/owner or roles/editor
            missing-required-role             — required_apis inferred but SA lacks role
            api-not-enabled                   — required_apis not in LiveState.enabled_apis
            scaling-cost-flag                 — min_scale > 0 with always-on cost risk
            unpinned-base-image               — base_image_pinned=False in DockerfileFacts
  [AMBIG]   ambiguous                         — Gemini 2.5 Pro classifies when no rule fires

SECURITY / FAIL-SAFE NOTES
--------------------------
  - §5: all three state objects are schema-validated before entering detection logic;
        raw GCP/repo content never reaches this agent.
  - §8: low confidence → delta_class = "needs-review", NEVER "will-fail".
        Prefer false negative over destructive false positive.
  - §3: summaries generated by the model MUST pass through the redaction seam (BE-07)
        before being written to session state; no secret values in any summary field.
  - confidence is ALWAYS emitted on every delta (required by contract).

MODEL
-----
  Gemini 2.5 Pro (MODEL_PRO) — reasoning tasks:
    (a) Ambiguity classification: delta_class = needs-review with explanation (LLM-03)
    (b) Human-readable summary generation per deterministic-detected delta
  The deterministic rule engine (BE-05) fires first; model is only for the residue.
"""

from __future__ import annotations

_AGENT_CLASS = None


def _get_agent_class():
    global _AGENT_CLASS  # noqa: PLW0603
    if _AGENT_CLASS is None:
        try:
            from google.adk.agents import Agent  # noqa: PLC0415
            _AGENT_CLASS = Agent
        except ImportError as exc:
            raise RuntimeError(
                "google-adk is not installed — run 'make install' to install dependencies."
            ) from exc
    return _AGENT_CLASS


def build_reconciler_agent():
    """
    Build and return the Reconciler ADK Agent.

    The Reconciler receives three schema-validated state dicts from session state and
    produces a list of ReconciliationDelta dicts.  It has NO registered tools — all
    detection runs deterministically in-process (BE-05 rule engine), and Gemini 2.5 Pro
    is called as an internal model call (not a tool) for ambiguity classification and
    human-readable explanation generation.

    Raises:
        RuntimeError: if google-adk is not installed.

    Returns:
        google.adk.agents.Agent: the constructed Reconciler agent.

    TODO (LLM-03, Increment 2): Wire the ambiguity layer — when no deterministic rule
    fires and the three sources are inconsistent in an unclassified way, call Gemini
    2.5 Pro with a structured JSON schema to classify as needs-review with explanation.
    Enforce fail-safe: output delta_class must be "needs-review", never "will-fail",
    for model-classified deltas.  Redact summaries before writing to session state.
    """
    from launchguard.config import MODEL_PRO  # noqa: PLC0415

    Agent = _get_agent_class()

    return Agent(
        name="Reconciler",
        model=MODEL_PRO,
        description=(
            "Diffs IntendedContract, DeclaredState, and LiveState to produce classified "
            "ReconciliationDelta objects.  Deterministic rule engine + Gemini 2.5 Pro for "
            "ambiguity residue.  No external tools.  Output written to session state key "
            "'reconciliation_deltas'."
        ),
        instruction=_RECONCILER_INSTRUCTION,
    )


_RECONCILER_INSTRUCTION = """\
You are Reconciler, the core sub-agent in the LaunchGuard three-source reconciliation pipeline.

YOUR SOLE JOB: compare the three state objects from session state and produce a list of
classified ReconciliationDelta objects.  Write the result to session state key:
reconciliation_deltas (a JSON array).

INPUTS FROM SESSION STATE:
  intended_contract  — what the code/Dockerfile require at runtime
  declared_state     — what the deploy config declares
  live_state         — what GCP actually grants

DETERMINISTIC DETECTION FIRST:
  The rule engine (running before you or alongside you) has already identified deterministic
  deltas.  Your role is to generate human-readable summaries and — ONLY IF the rule engine
  found no match for an inconsistency — to classify the ambiguity yourself.

AMBIGUITY CLASSIFICATION (only when no rule fires):
  If you detect an inconsistency that no deterministic rule covers:
  - Set delta_class = "needs-review" (NEVER "will-fail" for model-classified deltas)
  - Set confidence to reflect your uncertainty (0.5–0.8 range for genuine ambiguity)
  - Set rule_id = "ambiguous"
  - Provide a clear summary and recommendation

FAIL-SAFE (AI Operating Principles §8):
  When uncertain, UNDERCLASSIFY rather than overclassify.
  Low confidence ALWAYS maps to "needs-review".
  NEVER label a finding "will-fail" with confidence < 0.85 unless the deterministic
  rule engine has confirmed the gap (e.g., SA definitively lacks secretAccessor role).
  A missed finding (false negative) is less harmful than a wrong "will-fail" that
  triggers an unnecessary IAM change (expensive false positive).

REDACTION (AI Operating Principles §3):
  Your summary and recommendation fields MUST NOT contain secret values, tokens, passwords,
  or connection strings.  Reference secrets by NAME only (e.g., "SECRET_FOO").
  If you are unsure whether a value is sensitive, omit it and use "[REDACTED]".

EVIDENCE REQUIREMENT:
  Every delta MUST include at least one Evidence entry identifying WHICH source, WHICH
  locator (file:line, gcloud resource, service.yaml path), and a REDACTED snippet.
  No evidence = finding is not actionable.

DO NOT:
  - Call any tools (you have none — the allow-list is empty).
  - Make network calls or system calls.
  - Include secret values in any output field.
  - Emit confident "will-fail" for ambiguous cases.
"""
