#!/usr/bin/env bash
# Generated by devops-local agent on 2026-06-20
#
# CI-drift hash convention:
#   sha1sum .github/workflows/ci.yml
#   No CI workflow file exists yet for this project (capstone — no CI YAML at bootstrap).
#   When a CI workflow is added, re-run devops-local and record the sha1 here:
#   CI_YAML_SHA1=<hash>
#
# Replicates the local verification sequence: lint (ruff) → typecheck (mypy) → tests (pytest).
# Each stage: detect-if-installed → run-or-SKIP.
# Uses the existing ./venv interpreter explicitly (Python 3.12.3).
# Network installs are unreliable in this sandbox — missing tools are gracefully skipped.
#
# Usage:
#   bash scripts/local-ci.sh              # from repo root
#   make verify                           # calls this script

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_PYTHON="${REPO_ROOT}/venv/bin/python"
VENV_BIN="${REPO_ROOT}/venv/bin"

# Colour helpers (silent if terminal doesn't support)
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
ok()   { echo -e "${GREEN}[OK]${NC}    $*"; }
skip() { echo -e "${YELLOW}[SKIP]${NC}  $*"; }
fail() { echo -e "${RED}[FAIL]${NC}  $*"; }
info() { echo -e "         $*"; }

PYTHON_VERSION=$("${VENV_PYTHON}" --version 2>&1)

echo ""
echo "========================================"
echo " LaunchGuard — local-ci.sh"
echo " Python: ${PYTHON_VERSION}"
echo " Root:   ${REPO_ROOT}"
echo "========================================"
echo ""

# ------------------------------------------------------------------
# CLEAN STATE — remove stale build artefacts before any check.
# (CI always starts from a clean checkout; we replicate that here.)
# ------------------------------------------------------------------
info "Cleaning stale artefacts..."
find "${REPO_ROOT}" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
find "${REPO_ROOT}" -name "*.pyc" -delete 2>/dev/null || true
find "${REPO_ROOT}" -name ".mypy_cache" -type d -exec rm -rf {} + 2>/dev/null || true
find "${REPO_ROOT}" -name ".pytest_cache" -type d -exec rm -rf {} + 2>/dev/null || true
find "${REPO_ROOT}" -name ".ruff_cache" -type d -exec rm -rf {} + 2>/dev/null || true
ok "Clean state"
echo ""

# ------------------------------------------------------------------
# STAGE 1: Lint — ruff
# ------------------------------------------------------------------
echo "--- Stage 1: Lint (ruff) ---"
if "${VENV_BIN}/ruff" --version >/dev/null 2>&1; then
    RUFF_TARGETS=""
    [ -d "${REPO_ROOT}/launchguard" ] && RUFF_TARGETS="${RUFF_TARGETS} launchguard"
    [ -d "${REPO_ROOT}/eval" ]        && RUFF_TARGETS="${RUFF_TARGETS} eval"
    if [ -z "${RUFF_TARGETS}" ]; then
        skip "ruff — no source directories (launchguard/ eval/) exist yet; will lint when populated"
    else
        # shellcheck disable=SC2086
        "${VENV_BIN}/ruff" check --select=E,F,W,I ${RUFF_TARGETS}
        ok "ruff lint passed"
    fi
else
    skip "ruff not installed — run 'make install' to attempt installation"
fi
echo ""

# ------------------------------------------------------------------
# STAGE 2: Type-check — mypy
# ------------------------------------------------------------------
echo "--- Stage 2: Type-check (mypy) ---"
if "${VENV_BIN}/mypy" --version >/dev/null 2>&1; then
    MYPY_TARGETS=""
    [ -d "${REPO_ROOT}/launchguard" ] && MYPY_TARGETS="${MYPY_TARGETS} ${REPO_ROOT}/launchguard"
    if [ -z "${MYPY_TARGETS}" ]; then
        skip "mypy — no source directory launchguard/ exists yet"
    else
        # shellcheck disable=SC2086
        "${VENV_BIN}/mypy" \
            --python-executable "${VENV_PYTHON}" \
            --ignore-missing-imports \
            --no-error-summary \
            "${REPO_ROOT}/launchguard"
        ok "mypy passed"
    fi
else
    skip "mypy not installed — run 'make install' to attempt installation"
fi
echo ""

# ------------------------------------------------------------------
# STAGE 3: Tests — pytest
# ------------------------------------------------------------------
echo "--- Stage 3: Tests (pytest) ---"
if "${VENV_BIN}/pytest" --version >/dev/null 2>&1; then
    TEST_PATHS=""
    [ -d "${REPO_ROOT}/tests" ]  && TEST_PATHS="${TEST_PATHS} tests"
    [ -d "${REPO_ROOT}/eval" ]   && TEST_PATHS="${TEST_PATHS} eval"
    if [ -z "${TEST_PATHS}" ]; then
        skip "pytest — no test directories (tests/ eval/) exist yet; will run when populated"
    else
        # shellcheck disable=SC2086
        "${VENV_BIN}/pytest" \
            --tb=short \
            -q \
            ${TEST_PATHS}
        ok "pytest passed"
    fi
else
    skip "pytest not installed — run 'make install' to attempt installation"
fi
echo ""

echo "========================================"
echo " local-ci.sh complete."
echo " Stages that ran: $(grep -c '\[OK\]' /dev/stdin <<< "$(echo "")" || true)"
echo "========================================"
echo ""
